version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
  exchange-rate-service:
    image: exchange-rate-service:latest
    container_name: exchange-rate-service
    restart: unless-stopped
    ports:
      - "8080:8080"
